# Generated by Django 5.0.2 on 2024-02-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='name your project', max_length=50, verbose_name='main board title')),
                ('time_create', models.DateTimeField(auto_now_add=True, help_text='note create time', verbose_name='create time')),
                ('time_update', models.DateTimeField(auto_now=True, help_text='note last change time', verbose_name='update time')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Add title for your note', max_length=50, verbose_name='notes title')),
                ('text', models.TextField(help_text='Add text for your note', verbose_name='note text')),
                ('time_create', models.DateTimeField(auto_now_add=True, help_text='note create time', verbose_name='create time')),
                ('time_update', models.DateTimeField(auto_now=True, help_text='note last change time', verbose_name='update time')),
                ('files', models.FileField(blank=True, help_text='files for additional explanation', null=True, upload_to='files/', verbose_name='files storage')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='primary task title', max_length=50, verbose_name='title')),
                ('time_create', models.DateTimeField(auto_now_add=True, help_text='primary task create time', verbose_name='create time')),
                ('time_update', models.DateTimeField(auto_now=True, help_text='primary task last change time', verbose_name='update time')),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='subtask title', max_length=50, verbose_name='title')),
                ('time_create', models.DateTimeField(auto_now_add=True, help_text='subtask create time', verbose_name='create time')),
                ('time_update', models.DateTimeField(auto_now=True, help_text='subtask last change time', verbose_name='update time')),
                ('status', models.BooleanField(default=False, help_text='if subtask done - True, if not - False', verbose_name='subtask status')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='explanation title')),
                ('time_create', models.DateTimeField(auto_now_add=True, help_text='explanation create time', verbose_name='create time')),
                ('time_update', models.DateTimeField(auto_now=True, help_text='explanation last change time', verbose_name='update time')),
                ('files', models.FileField(blank=True, help_text='files for additional explanation', null=True, upload_to='files/', verbose_name='files storage')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='the status of the task. for example: to do, completed, etc', max_length=50, verbose_name='task status title')),
            ],
        ),
    ]
