# Generated by Django 5.0.2 on 2024-02-10 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mainboard',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='project author'),
        ),
        migrations.AddField(
            model_name='notes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='note author'),
        ),
        migrations.AddField(
            model_name='primarytask',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='primary task author'),
        ),
        migrations.AddField(
            model_name='mainboard',
            name='task',
            field=models.ForeignKey(help_text='primary tasks for main board', on_delete=django.db.models.deletion.CASCADE, to='boards.primarytask', verbose_name='primary tasks'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='subtask author'),
        ),
        migrations.AddField(
            model_name='primarytask',
            name='subtask',
            field=models.ForeignKey(help_text='subtask for primary task', on_delete=django.db.models.deletion.PROTECT, to='boards.subtask', verbose_name='subtask'),
        ),
        migrations.AddField(
            model_name='taskabout',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='explanation author'),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='subtask author'),
        ),
        migrations.AddField(
            model_name='primarytask',
            name='status',
            field=models.ForeignKey(help_text='for example: to do, completed, etc', on_delete=django.db.models.deletion.CASCADE, to='boards.taskstatus', verbose_name='primary task status'),
        ),
    ]
